name: Copy my CV to socc.io

on:
  # Run once per week
  schedule:
    - cron: '19 5 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Avoid running it at the same time as other "content" jobs
concurrency:
  group: "content"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
      - name: ssh keys
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_KEY_CV_LATEX_REPO }}'
      - name: Get cv-latex repo
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PRIVATE_KEY_CV_LATEX_REPO }}
          repository: michelinux/cv-latex
          ref: refs/heads/main
      - name: find cv.pdf
        run: find cv.pdf
      - name: Upload to socc.io via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          local_path: 'cv.pdf'
          remote_path: 'www/Michele_C_Soccio_CV.pdf'
          sftp_only: true
          password: ${{ secrets.PASSWORD }}
          ssh_private_key: null